$(document).ready(getProductosjson());
productos.addEventListener("click", sumarAlCarrito);
filtrado.addEventListener("click", sumarAlCarrito);
locales.addEventListener("click", elegirLocal);
puntoDeEntrega.addEventListener("click", reiniciarCompra);
sumaTotal.addEventListener("click", eliminarCarrito);
sumaTotal.addEventListener("click", GETlocales);
$("#toggle-btn").click(mostrarCarrito);
$("#eliminarfiltros").click(eliminarFiltro);
$("#ocb").click(filtroOCB);
$("#rolling").click(filtroRolling);
$("#papelillos").click(filtroPapelillos);
$("#filtros").click(filtroFiltros);
$("#pipas").click(filtroPipas);
$("#menorPrecio").click(filtroMenoraMayor);
$("#mayorPrecio").click(filtroMayoraMenor);
