$(document).ready(getProductosjson());
getLocalesjson();
productos.addEventListener("click", sumarAlCarrito);
filtrado.addEventListener("click", sumarAlCarrito);
sumaTotal.addEventListener("click", eliminarCarrito);
$("#toggle-btn").click(mostrarCarrito);
$("#eliminarfiltros").click(eliminarFiltro);
$("#ocb").click(filtroOCB);
$("#rolling").click(filtroRolling);
$("#papelillos").click(filtroPapelillos);
$("#filtros").click(filtroFiltros);
$("#pipas").click(filtroPipas);
$("#menorPrecio").click(filtroMenoraMayor);
$("#mayorPrecio").click(filtroMayoraMenor);
